Better lint integration in makefile

diff --git a/js/glsl-parser/Makefile b/js/glsl-parser/Makefile
--- a/js/glsl-parser/Makefile
+++ b/js/glsl-parser/Makefile
@@ -2,6 +2,7 @@ NODE_MODULES_BIN = ../../node_modules/.bin
 MOCHA_BIN = $(NODE_MODULES_BIN)/mocha
 _MOCHA_BIN = $(NODE_MODULES_BIN)/_mocha
 ISTANBUL_BIN = $(NODE_MODULES_BIN)/istanbul
+JSHINT_BIN = $(NODE_MODULES_BIN)/jshint
 
 MOCHA_OPTS = -u tdd
 T ?=
@@ -12,7 +13,7 @@ endif
 
 MOCHA = $(MOCHA_BIN) $(MOCHA_OPTS)
 
-TESTS = preprocessor_test.js ast_test.js sst_test.js
+TESTS = $(wildcard *_test.js)
 
 UNAME = $(shell uname)
 
@@ -32,6 +33,10 @@ $(ISTANBUL_BIN):
 	@echo 'Installing dependencies to run coverage using npm'; \
 	npm install --loglevel error istanbul >/dev/null
 
+$(JSHINT_BIN):
+	@echo 'Installing dependencies to run linter using npm'; \
+	npm install --loglevel error jshint >/dev/null
+
 test: $(MOCHA_BIN)
 	@$(MOCHA) $(TESTS)
 
@@ -48,4 +53,21 @@ test-coverage: $(MOCHA_BIN) $(ISTANBUL_BIN)
 	@$(ISTANBUL_BIN) cover $(_MOCHA_BIN) -- $(MOCHA_OPTS) -R spec $(TESTS) && \
 	$(OPEN) coverage/lcov-report/index.html
 
-.PHONY: all test test-ast test-preprocessor
+linter-func = 										\
+	printf "[\033[1mLINT\033[0m] ... ";				\
+	ret=$$($(JSHINT_BIN) $(wildcard *.js));			\
+	if [ $$? -ne 0 ]; then							\
+		printf "[\033[31mfail\033[0m]\n";			\
+		echo "$$ret";								\
+		exit 1;										\
+	else											\
+		printf "[\033[33mok\033[0m]\n";				\
+	fi
+
+linter: $(JSHINT_BIN)
+	@$(call linter-func)
+
+check: $(JSHINT_BIN) test
+	@$(call linter-func)
+
+.PHONY: all test test-ast test-sst test-preprocessor linter check
